/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "tertiary-container": "#004e5c",
        "on-secondary-fixed": "#00174b",
        "surface-container-highest": "#2d344c",
        "surface-container": "#181e36",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#003640",
        "on-secondary-fixed-variant": "#003ea8",
        "on-primary-container": "#725200",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#5c4200",
        "on-tertiary-fixed-variant": "#004e5c",
        "tertiary-fixed": "#acedff",
        "on-primary": "#402d00",
        "tertiary-fixed-dim": "#4cd7f6",
        "secondary-container": "#1d4ed8",
        "primary": "#ffe8c0",
        "tertiary": "#c6f2ff",
        "surface-container-low": "#141a32",
        "outline-variant": "#2a3656",
        "inverse-primary": "#7a5900",
        "outline": "#4b587c",
        "on-background": "#dce1ff",
        "surface-container-lowest": "#060d24",
        "background": "#0b1229",
        "primary-container": "#1d4ed8",
        "surface-tint": "#edc063",
        "error-container": "#93000a",
        "inverse-on-surface": "#292f48",
        "on-tertiary-container": "#acedff",
        "surface": "#0b1229",
        "error": "#ffb4ab",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#001f26",
        "primary-fixed-dim": "#edc063",
        "surface-container-high": "#222941",
        "secondary": "#38bdf8",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#261900",
        "surface-dim": "#0b1229",
        "surface-bright": "#323851",
        "primary-fixed": "#ffdea2",
        "on-secondary-container": "#dbe1ff",
        "on-surface": "#dce1ff",
        "inverse-surface": "#dce1ff",
        "surface-variant": "#2d344c",
        "on-surface-variant": "#a5b4d4",
        "royal": "#1d4ed8",
        "royal-dark": "#0e1a40",
        "sapphire": "#2563eb",
        "gold-fest": "#f6c86a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "2rem",
        "space-md": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "label-stamp": ["'Space Grotesk'", "sans-serif"],
        "title-editorial": ["'Space Grotesk'", "sans-serif"],
        "label-ticket": ["'Space Grotesk'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Bebas Neue'", "cursive"],
        "headline-sm": ["'Bebas Neue'", "cursive"],
        "display-hero": ["'Bebas Neue'", "cursive"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Bebas Neue'", "cursive"],
        "display-hero-mobile": ["'Bebas Neue'", "cursive"],
        "headline-md": ["'Bebas Neue'", "cursive"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "indie": ["'Syne'", "sans-serif"],
        "syne": ["'Syne'", "sans-serif"],
        "rozha": ["'Rozha One'", "serif"],
        "yatra": ["'Yatra One'", "cursive"]
      }
    },
  },
  plugins: [],
}
